### ISSUE TITLE
GZIP & CSO support

### ISSUE THREAD

**Issue by cascardian** [FaithLV/PCSX2-Spectabis#1]
One of the major reasons PCSX2Bonus slowly became unusable is the fact that it doesn't support loading GZIP- and CSO-compressed ISOs. As Spectabis becomes more developed, this should probably be  supported.

Avih discussed the implementation of GZIP here: http://forums.pcsx2.net/Thread-New-ISO-compression-help-testing
It was also mentioned in this progress report: http://pcsx2.net/269-major-gsdx-progress-monthly-reports.html
The CSO PR is here: https://github.com/PCSX2/pcsx2/pull/504

**Comment by valters-tomsons** [comment]
Thanks, will definitely look into it.

Edit: https://github.com/FaithLV/PCSX2-Spectabis/commit/b4adb177e9f40b739fc09cce5f84a2ba5452cb89
